// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Mock1.Model;

#nullable disable

namespace Mock1.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20240403035202_SeedVillaTable")]
    partial class SeedVillaTable
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Mock1.Model.Villa", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Amenity")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Occupancy")
                        .HasColumnType("int");

                    b.Property<double>("Rate")
                        .HasColumnType("float");

                    b.Property<DateTime>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Villas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Amenity = "Private pool, ocean view",
                            CreatedDate = new DateTime(2024, 4, 3, 10, 52, 1, 922, DateTimeKind.Local).AddTicks(9211),
                            Details = "This villa offers breathtaking views of the ocean and comes with a private pool.",
                            ImageUrl = "https://example.com/villa1.jpg",
                            Name = "Luxury Villa",
                            Occupancy = 8,
                            Rate = 500.0,
                            UpdatedDate = new DateTime(2024, 4, 3, 10, 52, 1, 922, DateTimeKind.Local).AddTicks(9226)
                        },
                        new
                        {
                            Id = 2,
                            Amenity = "Mountain view, fireplace",
                            CreatedDate = new DateTime(2024, 4, 3, 10, 52, 1, 922, DateTimeKind.Local).AddTicks(9229),
                            Details = "Escape to this cozy villa nestled in the mountains, perfect for a romantic getaway.",
                            ImageUrl = "https://example.com/villa2.jpg",
                            Name = "Cozy Retreat",
                            Occupancy = 4,
                            Rate = 300.0,
                            UpdatedDate = new DateTime(2024, 4, 3, 10, 52, 1, 922, DateTimeKind.Local).AddTicks(9230)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
